### ISSUE TITLE
Raspberry 4 not supported - Hardware revision is not supported

### ISSUE THREAD

**Issue by abstract-entity** [meg768/rpi-ws281x#12]
Hello,

Library is not working on my raspberry 4.

```
pi@raspberrypi:~/christmas $ sudo node player.js all-i-want-for-christmas.json all-i-want-for-ch                       ristmas.mp3
Loading track all-i-want-for-christmas.json
Configuring ws281x
/home/pi/christmas/node_modules/rpi-ws281x/index.js:77
        addon.configure({...options, leds:leds});
              ^

Error: configure(): ws2811_init() failed: Hardware revision is not supported
    at Module.configure (/home/pi/christmas/node_modules/rpi-ws281x/index.js:77:15)
    at Object.<anonymous> (/home/pi/christmas/player.js:28:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

It seems revision is missing for version 1.35 in 'rpihw.c'. My raspberry current revision: 
```
pi@raspberrypi:~/christmas $ cat /proc/cpuinfo | grep Revision
Revision        : b03114
```

I've check on project: https://github.com/jgarff/rpi_ws281x , the support for 0xb03114 (Pi 4, 2GB v1.4) have been added 3 november.

Can you update project with latest changes ? It will illuminate my house for Christmas !

Thank !

**Comment by rip3rs** [comment]
Not sure if this was fixed, but I have a RPI 4 and working with `rpi-ws281x` and is working as intended.

**Comment by chris-mck** [comment]
Only the Pi4 8GB model is supported. The upstream code in https://github.com/jgarff/rpi_ws281x/blob/master/rpihw.c added support for the 2GB, 4GB and CM4 8GB WiFi models that should be pulled in here.

**Comment by rip3rs** [comment]
This is so strange, after using this module without having to add the upstream code was working in about 6 RPI4 - 4GB / 2GB.

For some reason this new RPI's that I got simply stopped working. So I will be making a PR with the new upstream code

**Comment by abstract-entity** [comment]
> This is so strange, after using this module without having to add the upstream code was working in about 6 RPI4 - 4GB / 2GB.
> 
> For some reason this new RPI's that I got simply stopped working. So I will be making a PR with the new upstream code

Hey thanks good job, i'm not very familliar with C++.

I've try your PR (adding dependency in package.json: "rpi-ws281x": "git+https://github.com/meg768/rpi-ws281x.git#master"), this is working 1 time on 10, 

I got 'segmentation fault' or 'free(): invalid pointer' error randomly.

```
segmentation fault
```
Or
```
/home/pi/christmas/node_modules/rpi-ws281x/index.js:100
            addon.render(pixels, this.map);
                  ^

Error: Size of pixel mapping does not match.
    at Module.render (/home/pi/christmas/node_modules/rpi-ws281x/index.js:100:19)
    at Timeout._onTimeout (/home/pi/christmas/random-red-white.js:27:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
free(): invalid pointer
Aborted
```
Or
```
#
# Fatal error in , line 0
# Check failed: !backing_store->is_wasm_memory().
#
#
#
#FailureMessage Object: 0xbe8e5c30
Illegal instruction
```

Let me know how i can help, i'm very unfamilliar with c++

**Comment by rip3rs** [comment]
I haven't had any issues, could it be that you have an older package-lock?

Perhaps a repo with the project giving those errors, because I cannot seem to replicate :(
