### ISSUE TITLE
Brightness per Pixel

### ISSUE THREAD

**Issue by vanvanni** [meg768/rpi-ws281x#8]
Hi,

Is it possible with this **library** and the **WS2812B** strip to also set the brightness individually? If it is how can I achieve that?

**Comment by meg768** [comment]
Please explain. No not individual pixels...

**Comment by vanvanni** [comment]
@meg768 Yes set the brightness from a individual pixel on the strip? 

**Btw,** this is a great and awesome package for node. Amazing!

**Comment by meg768** [comment]
No, to do this you have to change the color of the pixel.

**Comment by revolunet** [comment]
Hi @meg768 what do you mean by change the color of the pixel ?
We should set global brightness to max and transform each color by lowering its brightness ?
How would you add Darkness to some hex color ?

**Comment by meg768** [comment]
Several color libraries are available at npm. https://www.npmjs.com/package/color is one example. It has a darken() method. 

<img width="649" alt="image" src="https://user-images.githubusercontent.com/4264015/98486143-db154e00-221b-11eb-958a-23244074aaca.png">

**Comment by revolunet** [comment]
Thanks thats great !
So we should set brightness initially to the max expected intensity ?
